### ISSUE TITLE
permission_denied() got an unexpected keyword argument 'code'

### ISSUE THREAD

**Issue by zumoshi** [sunscrapers/djoser#541]
Error while calling `/users/me/` endpoint with no/wrong auth.

Code in question:
https://github.com/sunscrapers/djoser/blob/35e5a5e75127d7270ab8f7bb13c4f7d0c0ec5a7b/djoser/views.py#L52
Code that calls it (from `django-rest-framework`):
https://github.com/encode/django-rest-framework/blob/be87eb43b348f1f079de81329218b79814b97173/rest_framework/views.py#L333
Change that added the `code` parameter:
https://github.com/encode/django-rest-framework/pull/7306

The only other issue I found about this was self closed: #538

Full trace:
```
Internal Server Error: /auth/users/me/
Traceback (most recent call last):
  File "C:\Users\Bor\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Bor\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Bor\AppData\Local\Programs\Python\Python38\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Bor\AppData\Local\Programs\Python\Python38\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Bor\AppData\Local\Programs\Python\Python38\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Bor\AppData\Local\Programs\Python\Python38\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Bor\AppData\Local\Programs\Python\Python38\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Bor\AppData\Local\Programs\Python\Python38\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\Bor\AppData\Local\Programs\Python\Python38\lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "C:\Users\Bor\AppData\Local\Programs\Python\Python38\lib\site-packages\rest_framework\views.py", line 333, in check_permissions
    self.permission_denied(
TypeError: permission_denied() got an unexpected keyword argument 'code'
```

**Comment by FairTraxx** [comment]
Same error, Roll back to a previous version the registration endpoint in the latest one appears to be broken...the rest works but they're useless at this point

**Comment by FairTraxx** [comment]
Not working on python 3.6.9 and generates the same error on 3.8.3
Also on /users/ endpoint

**Comment by FairTraxx** [comment]
I found the fix, apparently it's a problem with django rest framework version 3.12.1 downgrading to drf 3.11.1 will fix it.

**Comment by Jeketam** [comment]
Should djangorestframework<3.12.0 be specified in the README until the issue is fixed? 3.11.2 also worked when I tested.

**Comment by AlekseiKhatkevich** [comment]
same issue

**Comment by Tobeyforce** [comment]
Having the same issue on python 3.8.2 - will try downgrading. Good god I'm glad I found this thread, been confused for hours.

**Comment by sdebnath** [comment]
Is there a workaround or an issue opened with djangorestframework for this that we can track? I have a dependency on 3.12.2 so can't downgrade do 3.11.x.

**Comment by Aju100** [comment]
I got this same issue but try out the endpoints of it to create a user. It works.

**Comment by haxoza** [comment]
I confirm this issue. It appears locally within test suite.

**Comment by AlekseiKhatkevich** [comment]
Same issue

**Comment by anamargaridarl** [comment]
same issue here

**Comment by brandon-clair** [comment]
Apologies for raising an old issue, but this error has returned for those using Django 4.0. However, I've found a set of compatible package versions that will get around the issue (including JWT support). Here are the relevant bits from my Pipenv file:

```
django = "==4.0"
djangorestframework = "==3.12.4"
djoser = "==2.1.0"
djangorestframework-simplejwt = "==4.8.0"
```

This combination makes the error go away, but I haven't thoroughly tested it out. So, beware of potential problems due to the older JWT support and due to DRF being one release prior to its official Django 4 support.

**Comment by thubamamba** [comment]
I am currently faced with the same issue, here are my dependency versions below:

```bash
Django==4.0.5
djangorestframework==3.13.1
djangorestframework-simplejwt==5.2.0
djoser==2.0.5
```

**Comment by thubamamba** [comment]
In case anyone has the same issue with Django 4, you can install `Djoser 2.1.0`.

**Comment by Eadwulf** [comment]
I got the same problem using:
* Django 4.1.6
* Djoser  2.0.5
* DRF 3.14.0
<br>

I noticed the following:
<br>
when the `rest_framework.authentication.SessionAuthentication` is not set in the `DEFAULT_AUTHENTICATION_CLASSES` for `REST_FRAMEWORK` settings, the 'code' (<class 'str'>) is passed to the `djoser.views.UserViewSet.permission_denied` method. Such behavior, I think is undesirable because you could use either SessionAuthentication or TokenAuthentication.

My workaround was to modify the djoser.views.UserViewSet.permission_denied as follows:
<br>

```
class UserViewSet(viewsets.ModelViewSet):
    serializer_class = settings.SERIALIZERS.user
    queryset = User.objects.all()
    permission_classes = settings.PERMISSIONS.user
    token_generator = default_token_generator
    lookup_field = settings.USER_ID_FIELD

    def permission_denied(self, request, message=None, code=None): # Here added code=None
        if (
            settings.HIDE_USERS
            and request.user.is_authenticated
            and self.action in ["update", "partial_update", "list", "retrieve"]
        ):
            raise NotFound()
        super().permission_denied(request, message=message, code=None) # Here added code=None

```

With that, if you make a GET request with a token, you get the list of users.
